name: CI

# PNPM setup based on https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CI: true

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
            node-version: ">=22.8.0"
            check-latest: true
            cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Restore Turborepo cache
        id: cache-turborepo-restore
        uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-turborepo-${{ hashFiles('.turbo/cache') }}
          path: .turbo/cache

      - name: Restore ESLint root cache
        id: cache-eslint-root-restore
        uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-eslint-root-${{ hashFiles('node_modules/.cache/eslint') }}
          path: node_modules/.cache/eslint

      - name: Restore ESLint app cache
        id: cache-eslint-app-restore
        uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-eslint-app-${{ hashFiles('app/node_modules/.cache/eslint') }}
          path: app/node_modules/.cache/eslint

      - name: Restore ESLint libs cache
        id: cache-eslint-libs-restore
        uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-eslint-libs-${{ hashFiles('libs/**/node_modules/.cache/eslint') }}
          path: libs/**/node_modules/.cache/eslint

      - name: Restore TS root cache
        id: cache-ts-root-restore
        uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-ts-root-${{ hashFiles('node_modules/.cache/tsbuildinfo.json') }}
          path: node_modules/.cache/tsbuildinfo.json

      - name: Restore TS app cache
        id: cache-ts-app-restore
        uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-ts-app-${{ hashFiles('app/node_modules/.cache/tsbuildinfo.json') }}
          path: app/node_modules/.cache/tsbuildinfo.json

      - name: Restore TS app cache
        id: cache-ts-libs-restore
        uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-ts-libs-${{ hashFiles('libs/**/node_modules/.cache/tsbuildinfo.json') }}
          path: libs/**/node_modules/.cache/tsbuildinfo.json

      - name: Restore Jest libs cache
        id: cache-jest-libs-restore
        uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-jest-libs-${{ hashFiles('libs/**/node_modules/.cache/jest') }}
          path: libs/**/node_modules/.cache/jest

    #   - name: Cache Turborepo
    #     uses: actions/cache@v4
    #     with:
    #       path: node_modules/.cache/turbo
    #       key: ${{ runner.os }}-turbo-${{ github.sha }}
    #       restore-keys: |
    #         ${{ runner.os }}-turbo-
    #       save-always: true

    #   - name: Cache ESLint - Root
    #     uses: actions/cache@v4
    #     with:
    #       path: node_modules/.cache/eslint
    #       key: ${{ runner.os }}-eslint-root-${{ github.sha }}
    #       restore-keys: |
    #         ${{ runner.os }}-eslint-root
    #       save-always: true

    #   - name: Cache ESLint - App
    #     uses: actions/cache@v4
    #     with:
    #       path: app/node_modules/.cache/eslint
    #       key: ${{ runner.os }}-eslint-app-${{ github.sha }}
    #       restore-keys: |
    #         ${{ runner.os }}-eslint-app
    #       save-always: true

    #   - name: Cache ESLint - Libs
    #     uses: actions/cache@v4
    #     with:
    #       path: libs/**/node_modules/.cache/eslint
    #       key: ${{ runner.os }}-eslint-libs-${{ hashFiles('libs/**/node_modules/.cache/jest') }}
    #       save-always: true

    #   - name: Cache Jest
    #     uses: actions/cache@v4
    #     with:
    #       path: libs/**/node_modules/.cache/jest
    #       key: ${{ runner.os }}-jest-${{ hashFiles('libs/**/node_modules/.cache/jest') }}
    #       save-always: true

    #   - name: Cache TS - App
    #     uses: actions/cache@v4
    #     with:
    #       path: app/node_modules/.cache/tsbuildinfo.json
    #       key: ${{ runner.os }}-ts-app-${{ hashFiles('app/node_modules/.cache/tsbuildinfo.json') }}
    #       save-always: true

    #   - name: Cache TS - Libs
    #     uses: actions/cache@v4
    #     with:
    #       path: libs/**/node_modules/.cache/tsbuildinfo.json
    #       key: ${{ runner.os }}-ts-libs-${{ hashFiles('libs/**/node_modules/.cache/tsbuildinfo.json') }}
    #       save-always: true

      - name: Build app
        run: pnpm ci-build-app

      - name: Lint
        run: pnpm ci-lint

      - name: Save ESLint root cache
        id: cache-eslint-root-save
        if: always() && steps.cache-eslint-root-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.cache-eslint-root-restore.outputs.cache-primary-key }}
          path: node_modules/.cache/eslint

      - name: Save ESLint app cache
        id: cache-eslint-app-save
        if: always() && steps.cache-eslint-app-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.cache-eslint-app-restore.outputs.cache-primary-key }}
          path: app/node_modules/.cache/eslint

      - name: Save ESLint libs cache
        id: cache-eslint-libs-save
        if: always() && steps.cache-eslint-libs-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.cache-eslint-libs-restore.outputs.cache-primary-key }}
          path: libs/**/node_modules/.cache/eslint

      - name: Save TS root cache
        id: cache-ts-root-save
        if: always() && steps.cache-ts-root-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.cache-ts-root-restore.outputs.cache-primary-key }}
          path: node_modules/.cache/tsbuildinfo.json

      - name: Save TS app cache
        id: cache-ts-app-save
        if: always() && steps.cache-ts-app-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.cache-ts-app-restore.outputs.cache-primary-key }}
          path: app/node_modules/.cache/tsbuildinfo.json

      - name: Save TS libs cache
        id: cache-ts-libs-save
        if: always() && steps.cache-ts-libs-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.cache-ts-libs-restore.outputs.cache-primary-key }}
          path: libs/**/node_modules/.cache/tsbuildinfo.json

      - name: Test
        run: pnpm ci-test

      - name: Save Jest libs cache
        id: cache-jest-save
        if: always() && steps.cache-jest-libs-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.cache-jest-libs-restore.outputs.cache-primary-key }}
          path: libs/**/node_modules/.cache/jest

      - name: Save Turborepo cache
        id: cache-turborepo-save
        if: always() && steps.cache-turborepo-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.cache-turborepo-restore.outputs.cache-primary-key }}
          path: .turbo/cache
