name: CI

# PNPM setup based on https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CI: true

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
            node-version: ">=22.8.0"
            check-latest: true
            cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache Turborepo
        uses: actions/cache@v4
        with:
          path: node_modules/.cache/turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
          save-always: true

      - name: Cache ESLint - Root
        uses: actions/cache@v4
        with:
          path: node_modules/.cache/eslint
          key: ${{ runner.os }}-eslint-root-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-eslint-root
          save-always: true

      - name: Cache ESLint - App
        uses: actions/cache@v4
        with:
          path: app/node_modules/.cache/eslint
          key: ${{ runner.os }}-eslint-app-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-eslint-app
          save-always: true

      - name: Cache ESLint - Libs
        uses: actions/cache@v4
        with:
          path: libs/**/node_modules/.cache/eslint
          key: ${{ runner.os }}-eslint-libs-${{ hashFiles('libs/**/node_modules/.cache/jest') }}
          save-always: true

      - name: Cache Jest
        uses: actions/cache@v4
        with:
          path: libs/**/node_modules/.cache/jest
          key: ${{ runner.os }}-jest-${{ hashFiles('libs/**/node_modules/.cache/jest') }}
          save-always: true

      - name: Cache TS - App
        uses: actions/cache@v4
        with:
          path: app/node_modules/.cache/tsbuildinfo.json
          key: ${{ runner.os }}-ts-app-${{ hashFiles('app/node_modules/.cache/tsbuildinfo.json') }}
          save-always: true

      - name: Cache TS - Libs
        uses: actions/cache@v4
        with:
          path: libs/**/node_modules/.cache/tsbuildinfo.json
          key: ${{ runner.os }}-ts-libs-${{ hashFiles('libs/**/node_modules/.cache/tsbuildinfo.json') }}
          save-always: true

      - name: Build app
        run: pnpm ci-build-app

      - name: Lint
        run: pnpm ci-lint

      - name: Test
        run: pnpm ci-test
